name: Trigger External Workflow

on:
  push:
    branches:
      - master

env:
  HELM_EXPERIMENTAL_OCI: 1

permissions:
  contents: write
  pull-requests: write

jobs:
  reusable_workflow_job:
    uses: MapColonies/shared-workflows/.github/workflows/build-and-push.yaml@master
    secrets: inherit
  reusable_workflow_job_2:
    uses: MapColonies/shared-workflows/.github/workflows/bump-chart.yaml@master
    secrets: inherit